### ISSUE TITLE
BackArrow should vanish 

### ISSUE THREAD

**Issue by NBrestrich** [Electron-Microscope/electron-microscope#34]
#![bug](https://cloud.githubusercontent.com/assets/23233052/19961089/f1ea9aee-a1b0-11e6-8421-b91f3c36d44b.PNG)

Wen you are already in the Main Directory the Arrow should Vanish because wenn you click on it the Program will Show the loading Screen forever

**Comment by DevWurm** [comment]
What do you consider the main directory?

**Comment by NBrestrich** [comment]
![bug](https://cloud.githubusercontent.com/assets/23233052/19961976/b3f4ef96-a1b5-11e6-9700-baf22aa33993.PNG)

this is the last Screen wenn i click on the BackArrow again the loading Screen will Show forever and don't find anything

**Comment by DevWurm** [comment]
Maybe the directroy above is ver big? Maybe it just takes very long

**Comment by NBrestrich** [comment]
Maybe but over 30 min is a little bit to long^^

**Comment by NBrestrich** [comment]
but i thnk it is the Main because is the same like in the here
![bug2](https://cloud.githubusercontent.com/assets/23233052/19962382/9ddcfb5c-a1b7-11e6-9efa-cbc02b175de3.PNG)

**Comment by DevWurm** [comment]
The problem is, that the disk exploring process crashes when it tries to inspect irregular files or files with higher permissions. In this case the progress bar and the whole view is not updated anymore

**Comment by DevWurm** [comment]
Fixed
