### ISSUE TITLE
should that be so?

### ISSUE THREAD

**Issue by NBrestrich** [Electron-Microscope/electron-microscope#36]
![bug](https://cloud.githubusercontent.com/assets/23233052/19997379/6f197016-a266-11e6-9dc1-546eb6a5e32d.PNG)

**Comment by DevWurm** [comment]
Was it a single occurence or did it occure multiple times?

**Comment by DevWurm** [comment]
I was able to reproduce it, but I think it's not a bid deal, because it doesnt harm usability and functionality and hasn't a big impact on the design

**Comment by NBrestrich** [comment]
![bug2](https://cloud.githubusercontent.com/assets/23233052/19999299/cf1cfe0a-a271-11e6-8fdc-44eeee9a7a66.PNG)

you can create this error  so 
1.go with the mouse on a bar 
![bug](https://cloud.githubusercontent.com/assets/23233052/19999523/2df108d0-a273-11e6-9382-1f11608a4cf1.PNG)
2. than turn off the bar and the Point will stay 
![bug](https://cloud.githubusercontent.com/assets/23233052/19999666/02f1739e-a274-11e6-9a83-89234e076000.PNG)
